// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartTaxAssistant.Web.Data;

#nullable disable

namespace SmartTaxAssistant.Web.Migrations
{
    [DbContext(typeof(SmartTaxContext))]
    partial class SmartTaxContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartTaxAssistant.Web.Models.CorporateClient", b =>
                {
                    b.Property<int>("CorporateClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CorporateClientId"));

                    b.Property<string>("BusinessNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FiscalYearEnd")
                        .HasColumnType("DATE");

                    b.Property<DateTime?>("FiscalYearStart")
                        .HasColumnType("DATE");

                    b.Property<string>("IncorporationProvince")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LegalName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CorporateClientId");

                    b.ToTable("CorporateClients");
                });

            modelBuilder.Entity("SmartTaxAssistant.Web.Models.ExtractedLineItem", b =>
                {
                    b.Property<int>("ExtractedLineItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExtractedLineItemId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("LineNumber")
                        .HasColumnType("int");

                    b.Property<int>("PdfDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("RawText")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("TaxCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("TaxReturnId")
                        .HasColumnType("int");

                    b.HasKey("ExtractedLineItemId");

                    b.HasIndex("PdfDocumentId");

                    b.HasIndex("TaxCategoryId");

                    b.HasIndex("TaxReturnId");

                    b.ToTable("ExtractedLineItems");
                });

            modelBuilder.Entity("SmartTaxAssistant.Web.Models.PdfDocument", b =>
                {
                    b.Property<int>("PdfDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PdfDocumentId"));

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OriginalPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TaxReturnId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PdfDocumentId");

                    b.HasIndex("TaxReturnId");

                    b.ToTable("PdfDocuments");
                });

            modelBuilder.Entity("SmartTaxAssistant.Web.Models.QuestionnaireAnswer", b =>
                {
                    b.Property<int>("QuestionnaireAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionnaireAnswerId"));

                    b.Property<string>("AnswerText")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("QuestionnaireQuestionId")
                        .HasColumnType("int");

                    b.Property<int>("TaxReturnId")
                        .HasColumnType("int");

                    b.HasKey("QuestionnaireAnswerId");

                    b.HasIndex("QuestionnaireQuestionId");

                    b.HasIndex("TaxReturnId");

                    b.ToTable("QuestionnaireAnswers");
                });

            modelBuilder.Entity("SmartTaxAssistant.Web.Models.QuestionnaireQuestion", b =>
                {
                    b.Property<int>("QuestionnaireQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionnaireQuestionId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("ReturnType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("QuestionnaireQuestionId");

                    b.ToTable("QuestionnaireQuestions");
                });

            modelBuilder.Entity("SmartTaxAssistant.Web.Models.TaxCategory", b =>
                {
                    b.Property<int>("TaxCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaxCategoryId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ReturnType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TaxCategoryId");

                    b.ToTable("TaxCategories");
                });

            modelBuilder.Entity("SmartTaxAssistant.Web.Models.TaxReturn", b =>
                {
                    b.Property<int>("TaxReturnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaxReturnId"));

                    b.Property<int?>("CorporateClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("EstimatedBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReturnType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TaxYear")
                        .HasColumnType("int");

                    b.Property<int?>("TaxpayerId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalTaxPaid")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TaxReturnId");

                    b.HasIndex("CorporateClientId");

                    b.HasIndex("TaxpayerId");

                    b.ToTable("TaxReturns");
                });

            modelBuilder.Entity("SmartTaxAssistant.Web.Models.TaxRule", b =>
                {
                    b.Property<int>("TaxRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaxRuleId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ReturnType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TaxRuleId");

                    b.ToTable("TaxRules");
                });

            modelBuilder.Entity("SmartTaxAssistant.Web.Models.Taxpayer", b =>
                {
                    b.Property<int>("TaxpayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaxpayerId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("DATE");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResidencyProvince")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SIN")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TaxpayerId");

                    b.ToTable("Taxpayers");
                });

            modelBuilder.Entity("SmartTaxAssistant.Web.Models.ExtractedLineItem", b =>
                {
                    b.HasOne("SmartTaxAssistant.Web.Models.PdfDocument", "PdfDocument")
                        .WithMany("ExtractedLineItems")
                        .HasForeignKey("PdfDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartTaxAssistant.Web.Models.TaxCategory", "TaxCategory")
                        .WithMany("ExtractedLineItems")
                        .HasForeignKey("TaxCategoryId");

                    b.HasOne("SmartTaxAssistant.Web.Models.TaxReturn", null)
                        .WithMany("ExtractedLineItems")
                        .HasForeignKey("TaxReturnId");

                    b.Navigation("PdfDocument");

                    b.Navigation("TaxCategory");
                });

            modelBuilder.Entity("SmartTaxAssistant.Web.Models.PdfDocument", b =>
                {
                    b.HasOne("SmartTaxAssistant.Web.Models.TaxReturn", "TaxReturn")
                        .WithMany("PdfDocuments")
                        .HasForeignKey("TaxReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaxReturn");
                });

            modelBuilder.Entity("SmartTaxAssistant.Web.Models.QuestionnaireAnswer", b =>
                {
                    b.HasOne("SmartTaxAssistant.Web.Models.QuestionnaireQuestion", "QuestionnaireQuestion")
                        .WithMany("QuestionnaireAnswers")
                        .HasForeignKey("QuestionnaireQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartTaxAssistant.Web.Models.TaxReturn", "TaxReturn")
                        .WithMany()
                        .HasForeignKey("TaxReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionnaireQuestion");

                    b.Navigation("TaxReturn");
                });

            modelBuilder.Entity("SmartTaxAssistant.Web.Models.TaxReturn", b =>
                {
                    b.HasOne("SmartTaxAssistant.Web.Models.CorporateClient", "CorporateClient")
                        .WithMany("TaxReturns")
                        .HasForeignKey("CorporateClientId");

                    b.HasOne("SmartTaxAssistant.Web.Models.Taxpayer", "Taxpayer")
                        .WithMany("TaxReturns")
                        .HasForeignKey("TaxpayerId");

                    b.Navigation("CorporateClient");

                    b.Navigation("Taxpayer");
                });

            modelBuilder.Entity("SmartTaxAssistant.Web.Models.CorporateClient", b =>
                {
                    b.Navigation("TaxReturns");
                });

            modelBuilder.Entity("SmartTaxAssistant.Web.Models.PdfDocument", b =>
                {
                    b.Navigation("ExtractedLineItems");
                });

            modelBuilder.Entity("SmartTaxAssistant.Web.Models.QuestionnaireQuestion", b =>
                {
                    b.Navigation("QuestionnaireAnswers");
                });

            modelBuilder.Entity("SmartTaxAssistant.Web.Models.TaxCategory", b =>
                {
                    b.Navigation("ExtractedLineItems");
                });

            modelBuilder.Entity("SmartTaxAssistant.Web.Models.TaxReturn", b =>
                {
                    b.Navigation("ExtractedLineItems");

                    b.Navigation("PdfDocuments");
                });

            modelBuilder.Entity("SmartTaxAssistant.Web.Models.Taxpayer", b =>
                {
                    b.Navigation("TaxReturns");
                });
#pragma warning restore 612, 618
        }
    }
}
